### ISSUE TITLE
UX: Download a bucket/item/version of the flow from the registry

### ISSUE THREAD

**Issue by aperepel** [Chaffelson/nipyapi#30]
As a deployer I would like to issue a command to download a specific (or latest if version omitted) flow representation and save this artifact in a file. The file is to be in a format understood by another instance of the registry for import.

**Comment by aperepel** [comment]
Bonus points for allowing the deployer to specify mnemonic and friendly names path instead of using the uuids in the URI. Let the system lookup the actual IDs transparently.

**Comment by Chaffelson** [comment]
Working on this now, my logic flow is something like:

1. Get any version of any flow in any bucket (Effectively VersionedFlowSnapshot.flow_contents)
2. Deterministically seralise that Flow into YAML that can be diff'd
3. Export / Import the YAML safely

Bonus:
Might be able to make this work by coding enforcement of unique names for ProcessGroups and getting the user to pass in a set of parameters. Will think on it as I get import/export working

**Comment by aperepel** [comment]
Question. If the registry already has a representation json and metadata in it, why do we need to serialize to yaml? Or this json is not usable for import?

**Comment by Chaffelson** [comment]
@kevdoran may also have opinions here.
The Json needs to be pruned to be imported, as it contains the source object IDs and other information - so I don't think it makes sense to export the 'raw' object anyway. So this means we'd be doing some form of transformation on the object between the Registry and import/export anyway, so it may as well be useful.
Obviously transforming it from Json to another format introduces some complexity, and will require testing to ensure that no useful information is lost on the round trip. I think this is the same testing that will validate which format is more useful so I'm pushing forward with it.
The main argument for Yaml is that we are moving towards support for things like Ansible, which like to define configurations in Yaml. It makes sense to me to standardise all import/export functions on a single format to reduce code complexity and confusion for the user, so if I can use the same Yaml for import/export that we use for user-defined objects for import, then it's more consistent.
Obviously I need to thoroughly test both options, as at this point I do not know what will work with the API calls, but here's a un-pruned example object in both for you to compare.
First is Json:

```
pprint(ver_flow_snapshot_0.flow_contents)
{'comments': '',
 'component_type': 'PROCESS_GROUP',
 'connections': [],
 'controller_services': [],
 'funnels': [],
 'group_identifier': None,
 'identifier': '198075d5-84c8-3fe0-8afe-c831857a2155',
 'input_ports': [],
 'labels': [],
 'name': 'nipyapi_console_process_group_0',
 'output_ports': [],
 'position': {'x': 400.0, 'y': 400.0},
 'process_groups': [],
 'processors': [{'annotation_data': None,
                 'auto_terminated_relationships': ['success'],
                 'bulletin_level': 'WARN',
                 'bundle': {'artifact': 'nifi-standard-nar',
                            'group': 'org.apache.nifi',
                            'version': '1.5.0'},
                 'comments': '',
                 'component_type': 'PROCESSOR',
                 'concurrently_schedulable_task_count': 1,
                 'execution_node': 'ALL',
                 'group_identifier': '198075d5-84c8-3fe0-8afe-c831857a2155',
                 'identifier': 'cbf1d237-0b72-38cf-8bbf-3ecf44743781',
                 'name': 'nipyapi_console_processor_0',
                 'penalty_duration': '30 sec',
                 'position': {'x': 400.0, 'y': 400.0},
                 'properties': {'Batch Size': '1',
                                'Data Format': 'Text',
                                'File Size': '0B',
                                'Unique FlowFiles': 'false',
                                'character-set': 'UTF-8'},
                 'property_descriptors': {'Batch Size': {'display_name': 'Batch '
                                                                         'Size',
                                                         'identifies_controller_service': False,
                                                         'name': 'Batch Size'},
                                          'Data Format': {'display_name': 'Data '
                                                                          'Format',
                                                          'identifies_controller_service': False,
                                                          'name': 'Data '
                                                                  'Format'},
                                          'File Size': {'display_name': 'File '
                                                                        'Size',
                                                        'identifies_controller_service': False,
                                                        'name': 'File Size'},
                                          'Unique FlowFiles': {'display_name': 'Unique '
                                                                               'FlowFiles',
                                                               'identifies_controller_service': False,
                                                               'name': 'Unique '
                                                                       'FlowFiles'},
                                          'character-set': {'display_name': 'Character '
                                                                            'Set',
                                                            'identifies_controller_service': False,
                                                            'name': 'character-set'},
                                          'generate-ff-custom-text': {'display_name': 'Custom '
                                                                                      'Text',
                                                                      'identifies_controller_service': False,
                                                                      'name': 'generate-ff-custom-text'}},
                 'run_duration_millis': 0,
                 'scheduling_period': '1s',
                 'scheduling_strategy': 'TIMER_DRIVEN',
                 'style': {},
                 'type': 'org.apache.nifi.processors.standard.GenerateFlowFile',
                 'yield_duration': '1 sec'}],
 'remote_process_groups': [],
 'variables': {},
 'versioned_flow_coordinates': None}
```

And here's the Yaml version:

```yaml.dump(ver_flow_snapshot_0.flow_contents.to_dict(), sys.stdout)
identifier: 198075d5-84c8-3fe0-8afe-c831857a2155
name: nipyapi_console_process_group_0
comments: ''
position:
  x: 400.0
  y: 400.0
process_groups: []
remote_process_groups: []
processors:
- identifier: cbf1d237-0b72-38cf-8bbf-3ecf44743781
  name: nipyapi_console_processor_0
  comments: ''
  position:
    x: 400.0
    y: 400.0
  bundle:
    group: org.apache.nifi
    artifact: nifi-standard-nar
    version: 1.5.0
  style: {}
  type: org.apache.nifi.processors.standard.GenerateFlowFile
  properties:
    character-set: UTF-8
    File Size: 0B
    Batch Size: '1'
    Unique FlowFiles: 'false'
    Data Format: Text
  property_descriptors:
    character-set:
      name: character-set
      display_name: Character Set
      identifies_controller_service: false
    File Size:
      name: File Size
      display_name: File Size
      identifies_controller_service: false
    generate-ff-custom-text:
      name: generate-ff-custom-text
      display_name: Custom Text
      identifies_controller_service: false
    Batch Size:
      name: Batch Size
      display_name: Batch Size
      identifies_controller_service: false
    Unique FlowFiles:
      name: Unique FlowFiles
      display_name: Unique FlowFiles
      identifies_controller_service: false
    Data Format:
      name: Data Format
      display_name: Data Format
      identifies_controller_service: false
  annotation_data:
  scheduling_period: 1s
  scheduling_strategy: TIMER_DRIVEN
  execution_node: ALL
  penalty_duration: 30 sec
  yield_duration: 1 sec
  bulletin_level: WARN
  run_duration_millis: 0
  concurrently_schedulable_task_count: 1
  auto_terminated_relationships:
  - success
  component_type: PROCESSOR
  group_identifier: 198075d5-84c8-3fe0-8afe-c831857a2155
input_ports: []
output_ports: []
connections: []
labels: []
funnels: []
controller_services: []
versioned_flow_coordinates:
variables: {}
component_type: PROCESS_GROUP
group_identifier:
```

Both need to be deterministically ordered (probably alpha sort), and pruned of extra information, but I think the Yaml is fundamentally more approachable from a user perspective.
